In [34]:
import mysql.connector
from math import cos, asin, sqrt, pi
import pandas as pd
import numpy as np
from datetime import datetime

In [35]:
connection = mysql.connector.connect(
  host=endpoint,
  user=user,
  password=password,
  database="database"
)
cursor = connection.cursor()

In [36]:

testQuery = "select missions.id, missions.nodes from missions left join drones on drones.id = missions.drone_id"
test ="select missions.id, missions.nodes from missions join drones on drones.id = missions.drone_id"
cursor.execute(testQuery)
rows = cursor.fetchall()

In [37]:
def getGeometry(nodes):
    for x in range(len(nodes)):
        #print(nodesList[x])
        nodeQuery = f"select nodes.lat, nodes.lon, nodes.isIntersection from nodes where id = {nodes[x]}"
        cursor.execute(nodeQuery)
        geometry = cursor.fetchall()
        lat.append(geometry[0][0])
        lon.append(geometry[0][1])
        isIntersection.append(geometry[0][2])
        
def distance(lat1, lon1, lat2, lon2):
    p = pi/180
    a = 0.5 - cos((lat2-lat1)*p)/2 + cos(lat1*p) * cos(lat2*p) * (1-cos((lon2-lon1)*p))/2
    return 12742 * asin(sqrt(a))*1000
   
        
def getHorizontalDistance():
    sum = 0
    for x in range(len(lat)-1):
        sum+=distance(lat[x],lon[x],lat[x+1],lon[x+1])
    return sum

def convertToFloat():
    for x in range(len(lat)):
        lat[x] = float(lat[x])
        lon[x] = float(lon[x])

In [38]:
def timer(start_time=None):
    if not start_time:
        start_time = datetime.now()
        return start_time
    elif start_time:
        thour, temp_sec = divmod((datetime.now() - start_time).total_seconds(), 3600)
        tmin, tsec = divmod(temp_sec, 60)
        print('\n Time taken: %i hours %i minutes and %s seconds.' % (thour, tmin, round(tsec, 2)))

In [39]:
data = []
def ExtractFeatures():
    for index, r in enumerate(rows):
        global lat, lon, isInteresection
        lat, lon, isIntersection = [], [], []



        length = len(r[1])
        nodesList = r[1][1:length-1]
        nodesList = nodesList.split(',')

        getGeometry(nodesList)
        convertToFloat()


        data.append([int(getHorizontalDistance()),isIntersection.count(1),r[0]])


start_time = timer(None)
ExtractFeatures()
timer(start_time)

# xdist, ydist, intersections// speed, weight

 Time taken: 0 hours 1 minutes and 13.77 seconds.

In [51]:
data = np.array(data)

print(data)
dataFrame = pd.DataFrame({
    "mission_id": data[:,1],
    "x_distance": data[:,2],
    "intersections": data[:,0]
})

dataFrame.to_csv('training_data.csv', index = False)

[[   5  618 2137]
 [   7  619 1211]
 [   2  688 2121]
 [   0  689  325]
 [   0  690  240]
 [   4  691  908]
 [   8  692 1621]
 [  12  693 1948]
 [   4  694  836]
 [  10  695 1343]
 [  12  696 3486]
 [   0  697  205]
 [   9  698 1197]
 [   8  699 1685]
 [   0  700  514]
 [   8  701 1170]
 [   5  702 1110]
 [   7  703 1332]]

In [52]:
data=pd.read_csv('training_data.csv')
data.head(20)

    mission_id  x_distance  intersections
0          618        2137              5
1          619        1211              7
2          688        2121              2
3          689         325              0
4          690         240              0
5          691         908              4
6          692        1621              8
7          693        1948             12
8          694         836              4
9          695        1343             10
10         696        3486             12
11         697         205              0
12         698        1197              9
13         699        1685              8
14         700         514              0
15         701        1170              8
16         702        1110              5
17         703        1332              7